### ISSUE TITLE
[기능] 2단계 상세정보 모달 UI 구현

### ISSUE THREAD

**Issue by picoloman6** [boostcampwm-2022/web33-Mildo#20]
# 설명
- 상세정보 2단계 모달 및 하위 UI 구현
# 할 일
- [x]  박스 레이아웃 설정
- [ ]  지난 24시간 인구 정보 그래프 박스 UI 구현
- [ ]  내일 갈 거야 순위 박스 UI 구현

**Comment by bullmouse** [comment]
데이터를 백엔드로부터 받아서 그것을 기반으로 스타일링을 진행하기 위해 일단은 Open 상태로 두었습니다.
