### ISSUE TITLE
로딩 화면 렌더링

### ISSUE THREAD

**Issue by HyunJungJo98** [boostcampwm-2022/web33-Mildo#31]
# 설명
로딩 화면 렌더링
# 할 일

**Comment by bullmouse** [comment]
현재 재랜더링이 자주 되는 현상이 발생하고 있으며, 이 현상은 지금도 진행중입니다. 나중에 시간이 되면 랜더링이 자주 되는 현상을 리팩토링해서 없애볼 생각입니다.
